version: '3.7'

services:
  product-service:
    image: product-microservice:latest
    ports:
      - "8080:8080"
    networks:
      - my-network

  inventory-service:
    image: inventory-microservice:latest
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge